const {approach,depart,advance,build,upgrade,relocate}=require('./camp-helpers.cjs');
const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require('playwright');
const url=process.env.EMBERWILD_URL||'http://127.0.0.1:8765',out=path.resolve(__dirname,'../test-output');
const errors=[],external=[];
async function setup(browser,options){const ctx=await browser.newContext(options);await ctx.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(url).origin)return r.continue();external.push(r.request().url());return r.abort();});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/?qa=1');await p.evaluate(()=>emberwildQA.start());await p.waitForFunction(()=>emberwildQA.game);return{ctx,p};}
async function buy(p,id){await p.locator(`[data-buy="${id}"]`).click();await p.waitForFunction(()=>document.querySelector('#market-message')?.textContent.includes('已購買'));}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PBM_CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const {ctx,p}=await setup(browser,{viewport:{width:1440,height:1100}});
 await p.locator('#merchant').click();assert.equal(await p.locator('[data-buy]').count(),4);await buy(p,'wall');assert.equal(await p.evaluate(()=>emberwildQA.game.inventory.wall),2);assert.deepEqual(await p.evaluate(()=>emberwildQA.game.materials),{wood:5,bone:2});assert.equal(await p.evaluate(()=>emberwildQA.store.state.run.inventory.wall),2);
 console.log('PASS fixed merchant catalogue buys exact selected card and persists exact price');
 await p.evaluate(async()=>{emberwildQA.game.materials={wood:8,bone:8};await emberwildQA.checkpoint();emberwildQA.render();});
 await p.locator('[data-market-tab="hire"]').click();assert.equal(await p.locator('[data-buy]').count(),2);await buy(p,'hunter');assert.equal(await p.locator('[data-buy="guard"]').isDisabled(),true);assert.equal(await p.evaluate(()=>emberwildQA.game.amber),9);
 await p.locator('[data-action="market-close"]').click();await p.locator('#deck-hire').click();await p.evaluate(()=>{emberwildQA.game.nodes=[];});
 const a=await p.locator('[data-slot="0"]').boundingBox(),dest=await p.evaluate(()=>emberwildQA.painter.screen(240,300));await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(dest.x,dest.y,{steps:12});await p.mouse.up();await p.waitForFunction(()=>emberwildQA.store.state.run.allies.length===1);assert.equal(await p.evaluate(()=>emberwildQA.game.inventory.hunter),0);assert.equal(await p.evaluate(()=>emberwildQA.game.amber),9);
 console.log('PASS hire purchase then real drag deploys an ally with no double charging');
 await p.locator('#save-game').click();await p.reload();await p.locator('#continue-run').click();assert.equal(await p.evaluate(()=>emberwildQA.game.allies[0].type),'hunter');assert.equal(await p.evaluate(()=>emberwildQA.game.inventory.wall),2);assert.deepEqual(await p.evaluate(()=>emberwildQA.game.materials),{wood:4,bone:4});await p.locator('[data-action="resume"]').click();
 console.log('PASS refresh restores materials, inventory, selected deck and deployed companions');
 await advance(p);assert.equal(await p.locator('#merchant').isDisabled(),true);await p.evaluate(async()=>{const g=emberwildQA.game;g.enemies=[];g.spawnQueue=[];g.finishWave();g.amber=40;g.materials.bone=Math.max(g.materials.bone,10);emberwildQA.render();await emberwildQA.checkpoint();});assert.equal(await p.locator('[data-upgrade]').count(),0);assert.equal(await p.locator('#modal').isVisible(),false);await p.locator('#merchant').click();assert.equal(await p.locator('[data-buy]').count(),4);
 await p.locator('[data-market-tab="training"]').click();assert.equal(await p.locator('[data-buy]').count(),12);await buy(p,'skill-spring');assert.equal(await p.evaluate(()=>emberwildQA.game.mods.heal),1.5);assert.equal(await p.evaluate(()=>emberwildQA.game.inventory.spring),1);assert.equal(await p.locator('[data-buy="skill-spring"]').isDisabled(),true);
 console.log('PASS wave completion has no forced choice; all twelve training items can be browsed with no duplicate skill purchase');
 await p.locator('[data-market-tab="build"]').click();await p.screenshot({path:path.join(out,'08-merchant-desktop.png'),fullPage:true});
 const before=await p.evaluate(()=>emberwildQA.game.snapshot());await p.evaluate(()=>{const store=emberwildQA.store,base=store.storage;window.savedStorage=base;store.storage={getItem:k=>base.getItem(k),setItem(){throw Error('quota');}};});await p.locator('[data-buy="wall"]').click();await p.waitForSelector('[data-action="retry-save"]');assert.deepEqual(await p.evaluate(()=>emberwildQA.game.materials),before.materials);assert.deepEqual(await p.evaluate(()=>emberwildQA.game.inventory),before.inventory);await p.evaluate(()=>emberwildQA.store.storage=window.savedStorage);await p.locator('[data-action="retry-save"]').click();await p.locator('[data-action="resume"]').click();
 console.log('PASS failed browser save rolls purchase back and exposes retry instead of claiming success');
 await p.locator('#pause').click();await p.locator('[data-action="save-camp"]').click();await p.waitForSelector('#camp:not([hidden])');await p.evaluate(async()=>{await emberwildQA.store.mutate(s=>{const r=s.run;r.version=1;r.phase='draft';r.choices=['fire','armor','loot'];r.allies=[];delete r.allies;delete r.inventory;delete r.materials;r.hand=['torch','wall','nest','spring'];r.cardTimers=[0,0,0,0];});});await p.reload();await p.locator('#continue-run').click();assert.equal(await p.evaluate(()=>emberwildQA.game.phase),'prep');assert.equal(await p.evaluate(()=>emberwildQA.game.selectedUpgrades.includes('spring')),true);assert.equal(await p.locator('[data-upgrade]').count(),0);await ctx.close();
 console.log('PASS old draft save continues at preparation while retaining previously learned skills');
 const mobile=await setup(browser,{viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});const m=mobile.p;await m.evaluate(async()=>{emberwildQA.game.materials.bone=8;await emberwildQA.checkpoint();emberwildQA.render();});await m.locator('#merchant').tap();await m.locator('[data-market-tab="hire"]').tap();await m.screenshot({path:path.join(out,'09-merchant-mobile.png'),fullPage:true});await m.locator('[data-buy="guard"]').tap();await m.waitForFunction(()=>emberwildQA.game.inventory.guard===1);await m.locator('[data-action="market-close"]').tap();await m.locator('#deck-hire').tap();
 const cdp=await mobile.ctx.newCDPSession(m),card=await m.locator('[data-slot="1"]').boundingBox(),point=await m.evaluate(()=>{emberwildQA.game.nodes=[];return emberwildQA.painter.screen(240,300);});const from={x:card.x+card.width/2,y:card.y+card.height/2};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...from}]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:from.x+(point.x-from.x)*i/12,y:from.y+(point.y+55-from.y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.waitForFunction(()=>emberwildQA.game.allies.length===1);assert.equal(await m.evaluate(()=>emberwildQA.game.allies[0].type),'guard');assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await m.locator('#next-wave').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await m.screenshot({path:path.join(out,'10-companion-mobile.png'),fullPage:true});
 console.log('PASS mobile shop, contract purchase and real touch deployment fit the portrait screen');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS no browser exceptions or external requests');await mobile.ctx.close();
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
