const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium}=require('playwright'),{approach,depart}=require('./camp-helpers.cjs');
const url=process.env.EMBERWILD_URL||'http://127.0.0.1:8765',out=path.resolve(__dirname,'../test-output');fs.mkdirSync(out,{recursive:true});
const errors=[];
async function open(browser,options={}){const ctx=await browser.newContext(options),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await require('./camp-helpers.cjs').openVeteran(p,url+'/?qa=1');await p.evaluate(async()=>{await(await import('./painted-art.mjs')).preloadArt();});await p.locator('#begin').click();await p.waitForTimeout(120);return{ctx,p};}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PBM_CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const {ctx,p}=await open(browser,{viewport:{width:1440,height:1000}});
 await p.evaluate(async()=>{await emberwildQA.store.mutate(s=>{s.camp.loadout={cards:['watchtower','catapult','wall','hunter'],weapons:['axe'],skills:['volley']};});});
 assert.ok(await p.evaluate(async()=>Object.values((await import('./character-art.mjs')).characterStatus()).every(Boolean)));
 const before=await p.evaluate(()=>emberwildQA.campUI.walk.snapshot());await p.keyboard.down('d');await p.waitForFunction(()=>emberwildQA.campUI.painter.walkArt.state==='walk');await p.waitForTimeout(350);await p.screenshot({path:path.join(out,'22-moving-ranger.png')});await p.keyboard.up('d');
 await p.waitForFunction(()=>emberwildQA.campUI.painter.walkArt.state==='idle');const after=await p.evaluate(()=>emberwildQA.campUI.walk.snapshot());assert.ok(after.x>before.x+25);const phase=await p.evaluate(()=>emberwildQA.campUI.painter.walkArt.phase);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>emberwildQA.campUI.painter.walkArt.phase),phase);
 await p.keyboard.down('w');await p.waitForFunction(()=>emberwildQA.campUI.painter.walkArt.back===true);await p.waitForTimeout(200);await p.keyboard.up('w');assert.ok((await p.evaluate(()=>emberwildQA.campUI.walk.snapshot())).y<after.y);
 console.log('PASS actual keyboard walking, grounded idle, back-facing and step stop');
 await p.waitForFunction(()=>emberwildQA.campUI.painter.residents.snapshot().some(a=>a.status==='walk'),null,{timeout:15000});
 const statuses=await p.evaluate(()=>emberwildQA.campUI.painter.residents.snapshot());assert.equal(statuses.length,2);assert.ok(!statuses.some(a=>a.type==='merchant'));
 await approach(p,'merchant');await p.waitForSelector('[data-buy="watchtower"]');const frozen=await p.evaluate(()=>emberwildQA.campUI.painter.residents.snapshot());await p.waitForTimeout(220);assert.deepEqual(await p.evaluate(()=>emberwildQA.campUI.painter.residents.snapshot()),frozen);await p.locator('[data-action="market-close"]').click();
 console.log('PASS scheduled NPC walks, unique stationary merchant, modal pauses NPCs');
 await depart(p);const resume=p.locator('[data-action="resume"]');if(await resume.isVisible().catch(()=>false))await resume.click();assert.equal(await p.locator('#weapon').evaluate(el=>el.disabled),true);await p.evaluate(()=>{const g=emberwildQA.game;g.spawnEnemy('brute',{x:g.hero.x+140,y:g.hero.y});});await p.keyboard.press('j');await p.waitForFunction(()=>emberwildQA.game.hero.volleyCD>0);await p.waitForTimeout(170);await p.screenshot({path:path.join(out,'23-weapon-animation.png')});assert.equal(await p.evaluate(()=>emberwildQA.game.hero.weapon),'axe');
 await p.keyboard.press('Space');await p.waitForFunction(()=>emberwildQA.painter.walkArt.state==='dash');await p.waitForTimeout(280);assert.notEqual(await p.evaluate(()=>emberwildQA.painter.walkArt.state),'dash');
 console.log('PASS configured weapon, active skill and dash remain functional');await ctx.close();
 const {ctx:mobile,p:m}=await open(browser,{viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:2});
 const cdp=await mobile.newCDPSession(m),r=await m.locator('#camp-joystick').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:x+24,y:y-24}]});await m.waitForFunction(()=>emberwildQA.campUI.painter.walkArt.state==='walk');await m.waitForTimeout(200);await m.screenshot({path:path.join(out,'24-mobile-walk.png')});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await m.waitForFunction(()=>emberwildQA.campUI.painter.walkArt.state==='idle');assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.close();
 console.log('PASS mobile diagonal walking and touch cancellation settle correctly');
 // Render-only inspection page, separate from the game and its animation loop.
 const inspection=await browser.newPage({viewport:{width:1440,height:1000}});inspection.on('pageerror',e=>errors.push(e.message));await inspection.route('**/motion-inspect',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><body style="margin:0"><canvas width="1440" height="1000"></canvas></body>'}));await inspection.goto(url+'/motion-inspect');
 const frameResult=await inspection.evaluate(async()=>{const {preloadCharacters,drawCharacter}=await import('./character-art.mjs');await preloadCharacters();const c=document.querySelector('canvas').getContext('2d',{willReadFrequently:true});c.fillStyle='#546c4d';c.fillRect(0,0,1440,1000);const bounds=[];for(const [row,type]of ['ranger','porter','hunter'].entries())for(let i=0;i<8;i++){const phase=i/8,frame=1+Math.floor(phase*4)%4,runFrame=Math.floor(phase*5)%5;c.fillStyle='#fff';c.font='15px sans-serif';c.fillText(type+' '+(type==='ranger'?runFrame:frame),25+i*175,30+row*330);drawCharacter(c,type,80+i*175,270+row*330,{phase,frame,runFrame,moving:true,state:'walk',amount:1,stride:80,angle:.65,flip:false,back:false,lean:0},{height:190});}
  const small=document.createElement('canvas');small.width=small.height=300;const s=small.getContext('2d',{willReadFrequently:true});for(let runFrame=0;runFrame<5;runFrame++){s.clearRect(0,0,300,300);drawCharacter(s,'ranger',150,260,{frame:0,runFrame,moving:true,state:'walk',phase:runFrame/5,amount:1,stride:80,angle:.65,flip:false,back:false,lean:0},{height:180});const d=s.getImageData(0,0,300,300).data;let l=300,r=0,t=300,b=0;for(let y=0;y<300;y++)for(let x=0;x<300;x++)if(d[(y*300+x)*4+3]>20){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}bounds.push({l,r,t,b});}return bounds;});assert.equal(frameResult.length,5);assert.ok(Math.max(...frameResult.map(b=>b.b))-Math.min(...frameResult.map(b=>b.b))<=1);assert.ok(Math.max(...frameResult.map(b=>b.b-b.t))-Math.min(...frameResult.map(b=>b.b-b.t))<12);await inspection.screenshot({path:path.join(out,'21-continuous-walk-poses.png')});await inspection.close();
 console.log('PASS authored walk poses preserve foot baseline and stable character scale');
 const fallback=await browser.newPage();fallback.on('pageerror',e=>errors.push(e.message));await fallback.route(/assets\/motion-v[234]\/.*\.png/,r=>r.abort());await require('./camp-helpers.cjs').openVeteran(fallback,url+'/?qa=1');await fallback.locator('#begin').click();await fallback.keyboard.down('d');await fallback.waitForTimeout(180);await fallback.keyboard.up('d');assert.ok(await fallback.evaluate(()=>emberwildQA.campUI.walk.x)>980);await fallback.close();
 console.log('PASS missing animation atlas falls back without blocking movement');assert.deepEqual(errors,[]);console.log('PASS no JavaScript errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
