const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const{chromium}=require('playwright');const{approach,depart}=require('./camp-helpers.cjs');
const url=process.env.EMBERWILD_URL||'http://127.0.0.1:8765',out=path.resolve(__dirname,'../test-output');fs.mkdirSync(out,{recursive:true});
const errors=[];
async function ready(p){p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/?qa=1');await p.evaluate(async()=>{const a=await import('./painted-art.mjs');await a.preloadArt();});assert.ok(await p.evaluate(async()=>Object.values((await import('./painted-art.mjs')).artStatus()).every(Boolean)));await p.locator('#begin').click();}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PBM_CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1024}}),p=await context.newPage();await ready(p);
 const report=await p.evaluate(async()=>{const a=await import('./painted-art.mjs'),canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d',{willReadFrequently:true}),result=[];for(const key of Object.keys(a.SPRITES)){c.clearRect(0,0,128,128);const drawn=a.drawSprite(c,key,64,120,{height:110,width:110});const pixels=c.getImageData(0,0,128,128).data;let solid=0,empty=0;for(let i=3;i<pixels.length;i+=4){if(pixels[i]>120)solid++;if(!pixels[i])empty++;}result.push({key,drawn,solid,empty});}return result;});
 assert.equal(report.length,48);for(const r of report){assert.ok(r.drawn,r.key);assert.ok(r.solid>300,r.key+' has visible art');assert.ok(r.empty>4000,r.key+' has true transparency, not a rectangle');}
 console.log('PASS all 48 generated sprites load with real alpha and readable content');
 await p.evaluate(async()=>{await emberwildQA.store.mutate(s=>{s.camp.buildings=[{type:'tent',slot:0,level:2},{type:'forge',slot:1,level:2},{type:'nursery',slot:2,level:1},{type:'cache',slot:3,level:1}];});emberwildQA.campUI.render();});
 await p.screenshot({path:path.join(out,'14-painted-camp-desktop.png')});
 const before=await p.evaluate(()=>emberwildQA.campUI.walk.snapshot());await p.keyboard.down('d');await p.waitForTimeout(220);await p.keyboard.up('d');await p.keyboard.down('w');await p.waitForTimeout(170);await p.keyboard.up('w');assert.ok(await p.evaluate(()=>emberwildQA.campUI.walk.x)>before.x);assert.ok(await p.evaluate(()=>emberwildQA.campUI.walk.y)<before.y);assert.ok(await p.evaluate(()=>emberwildQA.campUI.painter.walkArt.step)>0);
 console.log('PASS painted ranger retains top-down movement and movement-driven animation');
 await approach(p,'plot-0');assert.equal(await p.locator('#modal-content .painted-icon image').getAttribute('href'),'assets/painted-v1/settlement-v2.png');await p.screenshot({path:path.join(out,'15-painted-facility.png')});await p.locator('[data-action="close-camp-site"]').click();
 await approach(p,'merchant');await p.waitForSelector('.merchant-art image');assert.equal(await p.locator('.merchant-art image').getAttribute('href'),'assets/painted-v1/residents.png');await p.screenshot({path:path.join(out,'16-painted-merchant.png')});await p.locator('[data-action="market-close"]').click();
 console.log('PASS facility panels and merchant portraits use the same generated art as the world');
 await depart(p);await p.locator('#weapon').click();assert.equal(await p.evaluate(()=>emberwildQA.game.hero.weapon),'axe');assert.equal(await p.locator('.equipped-weapon-art image').getAttribute('href'),'assets/painted-v1/weapons.png');await p.evaluate(()=>{const g=emberwildQA.game;g.spawnEnemy('brute',{x:g.hero.x+140,y:g.hero.y});});await p.keyboard.press('j');await p.waitForFunction(()=>emberwildQA.game.hero.volleyCD>0);await p.waitForTimeout(150);await p.screenshot({path:path.join(out,'17-painted-combat.png')});
 console.log('PASS independent painted weapon layer switches spear/axe in battle without changing gameplay');
 await context.close();
 const mobile=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true}),m=await mobile.newPage();await ready(m);await m.screenshot({path:path.join(out,'18-painted-camp-mobile.png')});await approach(m,'merchant');await m.waitForSelector('[data-buy="watchtower"]');await m.screenshot({path:path.join(out,'19-painted-merchant-mobile.png')});assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.close();
 console.log('PASS painted scene and merchant fit the portrait mobile viewport');
 const fallback=await browser.newPage();fallback.on('pageerror',e=>errors.push(e.message));await fallback.route('**/painted-v1/*.png',r=>r.abort());await fallback.goto(url+'/?qa=1');await fallback.locator('#begin').click();const x=await fallback.evaluate(()=>emberwildQA.campUI.walk.x);await fallback.keyboard.down('d');await fallback.waitForTimeout(180);await fallback.keyboard.up('d');assert.ok(await fallback.evaluate(()=>emberwildQA.campUI.walk.x)>x);await fallback.close();
 console.log('PASS blocked art loads retain geometric fallback and working controls');assert.deepEqual(errors,[]);console.log('PASS no JavaScript errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
