const {depart}=require('./camp-helpers.cjs');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium}=require('playwright');
const url=process.env.EMBERWILD_URL||'http://127.0.0.1:8765',out=path.resolve(__dirname,'../../../output/playwright');
fs.mkdirSync(out,{recursive:true});
const errors=[],external=[];
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.PBM_CHROME_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  try{
    const ctx=await browser.newContext({viewport:{width:1440,height:1100}});
    await ctx.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(url).origin)return r.continue();external.push(r.request().url());return r.abort();});
    const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
    await require('./camp-helpers.cjs').openVeteran(p,url+'/?qa=1');
    await p.locator('#begin').click();await depart(p);
    await p.locator('#merchant').click();
    assert.equal(await p.locator('[data-market-tab="shop"]').count(),1);
    assert.equal(await p.locator('[data-shop-offer="watchtower"]').count(),1);
    const before=await p.evaluate(()=>({inventory:{...emberwildQA.game.inventory},materials:{...emberwildQA.game.materials},amber:emberwildQA.game.amber,revision:emberwildQA.store.revision}));
    await p.locator('[data-shop-offer="watchtower"]').click();
    assert.equal(await p.locator('#shop-sheet').isVisible(),true);
    assert.match(await p.locator('#shop-checkout-title').textContent(),/確認支付/);
    await p.screenshot({path:path.join(out,'shop-checkout-desktop.png')});
    await p.locator('[data-action="shop-confirm"]').click();
    await p.waitForSelector('[data-action="shop-done"]');
    assert.match(await p.locator('#shop-checkout-title').textContent(),/演示完成/);
    const after=await p.evaluate(()=>({inventory:{...emberwildQA.game.inventory},materials:{...emberwildQA.game.materials},amber:emberwildQA.game.amber,revision:emberwildQA.store.revision,checkout:emberwildQA.shopCheckout.phase}));
    assert.deepEqual(after.inventory,before.inventory);
    assert.deepEqual(after.materials,before.materials);
    assert.equal(after.amber,before.amber);
    assert.equal(after.revision,before.revision);
    assert.equal(after.checkout,'done');
    await p.locator('[data-action="shop-done"]').click();
    assert.equal(await p.locator('#shop-sheet').count(),0);
    await p.locator('[data-market-tab="shop"]').click();
    assert.equal(await p.locator('[data-shop-offer="pack-fortify"]').count(),1);
    assert.equal(await p.locator('[data-buy]').count(),0);
    await p.locator('[data-shop-offer="pack-relic"]').click();
    await p.locator('[data-action="shop-cancel"]').click();
    const cancelled=await p.evaluate(()=>({inventory:{...emberwildQA.game.inventory},materials:{...emberwildQA.game.materials},amber:emberwildQA.game.amber}));
    assert.deepEqual(cancelled, {inventory:before.inventory,materials:before.materials,amber:before.amber});
    await p.screenshot({path:path.join(out,'shop-packs-desktop.png')});
    await ctx.close();
    const mobile=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});
    await mobile.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(url).origin)return r.continue();external.push(r.request().url());return r.abort();});
    const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));
    await require('./camp-helpers.cjs').openVeteran(m,url+'/?qa=1');
    await m.locator('#begin').tap();await depart(m,{});
    await m.locator('#merchant').tap();
    await m.locator('[data-market-tab="shop"]').tap();
    await m.locator('[data-shop-offer="pack-hire"]').tap();
    await m.screenshot({path:path.join(out,'shop-checkout-mobile.png')});
    await m.locator('[data-action="shop-confirm"]').tap();
    await m.waitForSelector('[data-action="shop-done"]');
    const mobileState=await m.evaluate(()=>({inventory:emberwildQA.game.inventory.hunter,amber:emberwildQA.game.amber}));
    assert.equal(mobileState.inventory,1);
    assert.equal(mobileState.amber,16);
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
    console.log('PASS card shop checkout is visual only and never grants cards');
    await mobile.close();
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
